### ISSUE TITLE
Allow a mapping between columns in data and geographies

### ISSUE THREAD

**Issue by virgesmith** [tgve/eAtlas#44]
e.g. 

`REACT_APP_GEOGRAPHY_COLUMN_NAME: msoa11cd` 

 means that both the data from `REACT_APP_DEFAULT_URL ` and `REACT_APP_GEOGRAPHY_URL` must share a common column name, which might require manual editing of the data. 

Would it be possible to specify this as a dict, e.g.

```
REACT_APP_GEOGRAPHY_COLUMN_NAME: msoa11cd: MSOA
```
(apologies if my yaml syntax is a bit off) 

then I could keep the original column name ("MSOA") in the data?

Thanks!

**Comment by layik** [comment]
Thanks @virgesmith. This is a must really but as you know early days so apologies for the strict rule for now.

**Comment by layik** [comment]
The above commit stipulates this format `dataCol:geoCol` so data (csv etc) must come frist, then comes the geography column name. This should be safe `samename:samename` but redundant.
