### ISSUE TITLE
tgve/eAtlas branch revamp/restructure - discuss

### ISSUE THREAD

**Issue by layik** [tgve/eAtlas#96]
For clarification, the branch was the main dev repo for eAtlas/TGVE and has now grown out of its purpose.

- master branch is now way behind branch `npm`
- branch `npm` is the most important part, `npm-dev` is where I do work and create PRs on `npm`.
- Wiki is the main docs for "the project"
- Dockerfile is based on "old" approach of building the front-end using JS tools (npm)

Must be done:
- README to serve as pointer to Wiki/docs and other repo docs etc
- master branch => `npm` branch?
- etc

Consider doing:
- ??

**Comment by rolyp** [comment]
@layik Moved this from the `reg` repo and will consolidate into #64.

**Comment by rolyp** [comment]
Merged into #64
